spring:
  profiles:
    active: dev
mybatis:
  type-aliases-package: io.yorkecao.springbootdemo.model
  mapper-locations: classpath:io/yorkecao/springbootdemo/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring-boot-demo:
  name: name